import { useCallback, useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { api } from "../api";

interface WebsiteBrief {
  id: string;
  leadId: string;
  opportunityId: string | null;
  websiteUrl: string | null;
  weaknesses: string[];
  buildPrompt: string;
  recommendedStack: { libs: string[]; plugins: string[] };
  targetModel: string;
  generatedBy: string;
  repoUrl: string | null;
  status: "ready" | "shipped";
  createdAt: string;
}

function BriefCard({ brief, onChanged }: { brief: WebsiteBrief; onChanged: () => void }) {
  const [repoUrl, setRepoUrl] = useState(brief.repoUrl ?? "");
  const [copied, setCopied] = useState(false);
  const [error, setError] = useState("");
  const [note, setNote] = useState("");

  const copyPrompt = async () => {
    try {
      await navigator.clipboard.writeText(brief.buildPrompt);
      setCopied(true);
      setTimeout(() => setCopied(false), 1500);
    } catch {
      setError("Clipboard unavailable — select the text manually.");
    }
  };

  const markReady = async () => {
    setError("");
    setNote("");
    try {
      await api(`/api/website-briefs/${brief.id}/ship`, { method: "POST", body: JSON.stringify({ repoUrl: repoUrl.trim() }) });
      setNote("Ship requested — approve DEPLOY_PRODUCTION in the Review Queue to publish and draft the delivery email.");
      onChanged();
    } catch (err) {
      setError(err instanceof Error ? err.message : "ship request failed");
    }
  };

  return (
    <div className="panel">
      <h3>
        Brief for <Link to={`/leads/${brief.leadId}`}>{brief.leadId.slice(-8)}</Link>{" "}
        <span className={`badge ${brief.status === "shipped" ? "blue" : "green"}`}>{brief.status}</span>{" "}
        <span className="badge">target: {brief.targetModel}</span>{" "}
        <span className="sub">generated by {brief.generatedBy}</span>
      </h3>
      {brief.websiteUrl && <p className="sub">Current site: {brief.websiteUrl}</p>}
      {brief.weaknesses.length > 0 && (
        <p className="sub">Fixing: {brief.weaknesses.slice(0, 4).join("; ")}{brief.weaknesses.length > 4 ? "…" : ""}</p>
      )}
      <div className="toolbar">
        <button className="primary" onClick={copyPrompt}>{copied ? "Copied!" : "Copy build prompt"}</button>
        <span className="sub">Paste into Fable 5 / Opus 4.8 to build the site.</span>
      </div>
      <textarea readOnly value={brief.buildPrompt} rows={12} style={{ width: "100%", fontFamily: "monospace", fontSize: 12 }} />

      {brief.status === "ready" ? (
        <div className="toolbar" style={{ marginTop: 10 }}>
          <input
            placeholder="Finished repo URL (https://github.com/owner/repo)"
            value={repoUrl}
            onChange={(e) => setRepoUrl(e.target.value)}
            style={{ minWidth: 360 }}
          />
          <button className="approve" onClick={markReady} disabled={!repoUrl.trim()}>Mark website ready</button>
        </div>
      ) : (
        <p className="sub" style={{ marginTop: 10 }}>Shipped from {brief.repoUrl}</p>
      )}
      {note && <div className="sub" style={{ color: "var(--green, green)" }}>{note}</div>}
      {error && <div className="error">{error}</div>}
    </div>
  );
}

export function WebsiteBriefs() {
  const [briefs, setBriefs] = useState<WebsiteBrief[]>([]);
  const refresh = useCallback(() => {
    api<{ items: WebsiteBrief[] }>("/api/collections/website-briefs?limit=200").then((r) => setBriefs(r.items));
  }, []);
  useEffect(refresh, [refresh]);

  return (
    <>
      <h2>Website Briefs</h2>
      <p className="sub">
        On a positive reply, William generates a build prompt for the owner to run on Fable 5 / Opus 4.8. Copy the
        prompt, build the site, then paste the finished repo URL and mark it ready — shipping needs your
        DEPLOY_PRODUCTION approval and then drafts the delivery email.
      </p>
      {briefs.map((b) => <BriefCard key={b.id} brief={b} onChanged={refresh} />)}
      {briefs.length === 0 && <div className="panel"><p className="empty">No briefs yet — they appear after a positive reply.</p></div>}
    </>
  );
}
